# Generated by Django 6.1 on 2026-08-25 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DebitCardEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CityEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmApp.countryentity')),
            ],
        ),
        migrations.CreateModel(
            name='HotelEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200, unique=True)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('stars', models.IntegerField(default=0)),
                ('photo', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmApp.cityentity')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethodEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardNumber', models.CharField(max_length=10, unique=True)),
                ('date', models.DateField()),
                ('cardType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmApp.debitcardentity')),
            ],
        ),
        migrations.CreateModel(
            name='RoomEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomNumber', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('wifi', models.BooleanField(default=False)),
                ('privatePool', models.BooleanField(default=False)),
                ('Bath', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('beds', models.IntegerField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmApp.hotelentity')),
            ],
        ),
        migrations.CreateModel(
            name='UserEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('hashPassword', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('phone', models.CharField(blank=True, max_length=200, unique=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('photo', models.CharField(blank=True, max_length=200, unique=True)),
                ('ampthill', models.CharField(blank=True, max_length=200)),
                ('authCode', models.CharField(blank=True, max_length=200)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bmApp.cityentity')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bmApp.currencyentity')),
                ('payMethod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bmApp.paymentmethodentity')),
            ],
        ),
        migrations.CreateModel(
            name='ReservationEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkIn', models.DateField()),
                ('checkOut', models.DateField()),
                ('name', models.CharField(max_length=200)),
                ('sureName', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(blank=True, max_length=200)),
                ('phoneNumber', models.CharField(max_length=200, unique=True)),
                ('cityGuide', models.BooleanField(default=False)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bmApp.countryentity')),
                ('payMethod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bmApp.paymentmethodentity')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmApp.roomentity')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bmApp.userentity')),
            ],
        ),
    ]
