# Generated by Django 6.1 on 2026-08-27 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userentity',
            name='authCodeCreatedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userentity',
            name='created',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userentity',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='ReviewEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('createdAt', models.DateTimeField()),
                ('rating', models.IntegerField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmApp.hotelentity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmApp.userentity')),
            ],
        ),
    ]
