# Generated by Django 6.1 on 2026-08-29 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmApp', '0002_userentity_authcodecreatedat_userentity_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomentity',
            name='photo',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
