# Generated by Django 6.1 on 2026-09-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmApp', '0003_roomentity_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityentity',
            name='center',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
