# Generated by Django 6.1 on 2026-09-17 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmApp', '0004_cityentity_center'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomentity',
            old_name='Bath',
            new_name='bath',
        ),
    ]
