# Generated by Django 6.1 on 2026-09-07 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmApp', '0004_cityentity_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelentity',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='hotelentity',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
    ]
