# Generated by Django 6.1 on 2026-09-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmApp', '0005_hotelentity_latitude_hotelentity_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityentity',
            name='center_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='cityentity',
            name='center_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
