# Generated by Django 6.1 on 2026-09-16 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmApp', '0006_cityentity_center_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelentity',
            name='nearest_airport_distance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotelentity',
            name='nearest_train_distance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
