# Generated by Django 6.1 on 2026-09-16 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmApp', '0007_hotelentity_nearest_airport_distance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelentity',
            name='stars',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='roomentity',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10),
        ),
    ]
