# Generated by Django 6.1 on 2026-09-18 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmApp', '0005_rename_bath_roomentity_bath'),
        ('bmApp', '0008_alter_hotelentity_stars_alter_roomentity_price'),
    ]

    operations = [
    ]
