# Generated by Django 6.1 on 2026-09-19 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmApp', '0010_alter_userentity_phone_and_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomentity',
            old_name='bath',
            new_name='Bath',
        ),
    ]
