# Generated by Django 6.1 on 2026-09-22 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmApp', '0011_rename_bath_roomentity_bath'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethodentity',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bmApp.userentity'),
        ),
        migrations.AddField(
            model_name='reservationentity',
            name='allowChangeBooking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservationentity',
            name='confirmByCall',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservationentity',
            name='confirmByEmail',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservationentity',
            name='totalPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethodentity',
            name='cardNumber',
            field=models.CharField(max_length=19, unique=True),
        ),
        migrations.AlterField(
            model_name='reservationentity',
            name='email',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='reservationentity',
            name='phoneNumber',
            field=models.CharField(max_length=200),
        ),
    ]
