# Generated by Django 6.1 on 2026-09-22 19:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmApp', '0012_paymentmethodentity_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationentity',
            name='viewToken',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
